name: confessions
description: "Listen and share your confessions"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  appwrite: ^24.0.0
  audio_session: ^0.2.3
  cupertino_icons: ^1.0.8
  file_picker: ^11.0.2
  firebase_analytics: ^12.4.0
  firebase_core: ^4.8.0
  firebase_crashlytics: ^5.2.1
  firebase_messaging: ^16.2.1
  firebase_performance: ^0.11.4
  firebase_remote_config: ^6.5.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  path: ^1.9.1
  path_provider: ^2.1.5
  purchase_service: ^1.0.1
  record: ^6.2.0
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/legal/
